### ISSUE TITLE
Plugin isn't working with Vue files

### ISSUE THREAD

**Issue by salvadornico** [prograhammer/vscode-tslint-vue#13]
This appears in the output console as soon as I start up VSCode:

```
[Info  - 10:07:41 PM] Linter is running.
[Info  - 10:07:42 PM] TSLint library loaded from: c:\Development\elie\node_modules\tslint\lib\index.js
TypeError: Cannot read property 'text' of undefined
    at getErrorSpanForNode (c:\Development\elie\node_modules\typescript\lib\typescript.js:8305:39)
    at createDiagnosticForNodeInSourceFile (c:\Development\elie\node_modules\typescript\lib\typescript.js:8230:20)
    at Object.createDiagnosticForNode (c:\Development\elie\node_modules\typescript\lib\typescript.js:8226:16)
    at error (c:\Development\elie\node_modules\typescript\lib\typescript.js:25081:22)
    at resolveExternalModule (c:\Development\elie\node_modules\typescript\lib\typescript.js:26311:25)
    at resolveExternalModuleNameWorker (c:\Development\elie\node_modules\typescript\lib\typescript.js:26249:20)
    at mergeModuleAugmentation (c:\Development\elie\node_modules\typescript\lib\typescript.js:25237:34)
    at initializeTypeChecker (c:\Development\elie\node_modules\typescript\lib\typescript.js:47446:25)
    at Object.createTypeChecker (c:\Development\elie\node_modules\typescript\lib\typescript.js:24920:9)
    at getDiagnosticsProducingTypeChecker (c:\Development\elie\node_modules\typescript\lib\typescript.js:74460:93)
```

Any idea what's going on?

**Comment by SimonAKing** [comment]
I also met this problem, don't know what to do.
