### ISSUE TITLE
Trying to set up tslint-vue, but getting an error running it on any .vue file

### ISSUE THREAD

**Issue by dkulchenko** [prograhammer/vscode-tslint-vue#5]
```
[Info  - 11:10:22] vscode-tslint: 'Path must be a string. Received undefined' while validating: /Users/daniilk/code/front/src/components/ForgotPassword.vue stacktrace: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at getParsedTsConfig (/Users/daniilk/.vscode/extensions/prograhammer.tslint-vue-1.4.2/server/server.js:544:127)
    at createProgram (/Users/daniilk/.vscode/extensions/prograhammer.tslint-vue-1.4.2/server/server.js:458:20)
    at /Users/daniilk/.vscode/extensions/prograhammer.tslint-vue-1.4.2/server/server.js:420:31
    at Generator.next (<anonymous>)
    at fulfilled (/Users/daniilk/.vscode/extensions/prograhammer.tslint-vue-1.4.2/server/server.js:7:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

There is a tsconfig.json file in the project, but it's not at the workspace root (workspace root/code/front <- in here).

**Comment by prograhammer** [comment]
Ah yeah, that's a flexibility problem. It wants your config at the workspace root and also wants src at `[workspace root]/src`. I'm looking to have **v2.0.0** out in the next day or so (see [this issue](https://github.com/prograhammer/vscode-tslint-vue/issues/4)) so I'll take care of that then and close this issue then. Hang in there a bit more.

**Comment by prograhammer** [comment]
@dkulchenko If you want a quick hack for the meantime, search for your `.vscode/extensions/prograhammer...` folder and open up `server/server.js`. If in latest version (v1.4.2). Modify the line #518 and hard code in the path to your `src/` folder.

**Comment by prograhammer** [comment]
@dkulchenko And checkout line #532 to hardcode `tsconfig.json`. Flexibility coming in version 2. Stay tuned.

**Comment by dkulchenko** [comment]
That does the trick for now - thanks so much! Will wait eagerly for v2.
